"""add administrator at users

Revision ID: 77c1612ce64d
Revises: 4cdb29ff1d7a
Create Date: 2022-04-29 08:12:39.650787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c1612ce64d'
down_revision = '4cdb29ff1d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_administrator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_administrator')
    # ### end Alembic commands ###
