"""delete mlem

Revision ID: e4f7df5d4abb
Revises: 0365aa43dc5f
Create Date: 2022-04-29 08:18:02.490709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f7df5d4abb'
down_revision = '0365aa43dc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'mlem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mlem', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
